In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [2]:
data=pd.read_csv('census-income_(1).csv',skipinitialspace=True)

In [3]:
data= data.replace('?',np.nan)

In [4]:
data.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
Unnamed: 14          0
dtype: int64

In [5]:
data=data.rename(columns={'Unnamed: 14': 'AnnualIncome'})

In [6]:
data[(data['workclass']=='Private') & (data['native-country']!='United-States')].shape

(2561, 15)

In [7]:
census_ed=data['education']

In [8]:
census_ed

0         Bachelors
1         Bachelors
2           HS-grad
3              11th
4         Bachelors
            ...    
32556    Assoc-acdm
32557       HS-grad
32558       HS-grad
32559       HS-grad
32560       HS-grad
Name: education, Length: 32561, dtype: object

In [9]:
census_seq=data.iloc[:,:8]

In [10]:
census_seq

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship  
0           Never-married       Adm-clerical  Not-in-family  
1      Married-civ-spouse    Exec-managerial        Husband  
2                Divorced  Handlers-cleaners  Not-in-family  
3      Married-civ-spouse  Handlers-cleaners        Husband  
4      Married-civ-spouse     Prof-specialty           Wife  
...                   ...                ...            ...  
32556  Married-civ-spouse       Tech-support           Wife  
32557  Married-civ-spouse  Machine-op-inspct        Husband  
32558             Widowed       Adm-clerical      Unmarried  
32559       Never-married       Adm-clerical      Own-child  
32560  Married-civ-spouse    Exec-managerial           Wife  

[32561 rows x 8 columns]

In [11]:
census_col=data.iloc[:,[5,8,11]]
census_col

marital-status   race  capital-loss
0           Never-married  White             0
1      Married-civ-spouse  White             0
2                Divorced  White             0
3      Married-civ-spouse  Black             0
4      Married-civ-spouse  Black             0
...                   ...    ...           ...
32556  Married-civ-spouse  White             0
32557  Married-civ-spouse  White             0
32558             Widowed  White             0
32559       Never-married  White             0
32560  Married-civ-spouse  White             0

[32561 rows x 3 columns]

In [12]:
data.head(2)

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   

       marital-status       occupation   relationship   race   sex  \
0       Never-married     Adm-clerical  Not-in-family  White  Male   
1  Married-civ-spouse  Exec-managerial        Husband  White  Male   

   capital-gain  capital-loss  hours-per-week native-country AnnualIncome  
0          2174             0              40  United-States        <=50K  
1             0             0              13  United-States        <=50K

In [13]:
male_gov=data[(data['sex']=='Male') & (data['workclass']=='State-gov')]

In [14]:
census_us=data[(data['age']==39)& ((data['education']=='Bachelors') |(data['native-country']=='United-States'))]

In [15]:
census_200=data.sample(200)
census_200

age         workclass  fnlwgt     education  education-num  \
28404   41           Private  157025       HS-grad              9   
22674   19           Private   67759       HS-grad              9   
13386   32  Self-emp-not-inc  203408       HS-grad              9   
22936   46           Private  123598     Bachelors             13   
26859   26           Private  160300       HS-grad              9   
...    ...               ...     ...           ...            ...   
13419   61           Private   51385     Bachelors             13   
26348   59               NaN  375049       HS-grad              9   
23605   20           Private  127185  Some-college             10   
18762   31           Private  156493       HS-grad              9   
25354   65           Private   89681       Masters             14   

           marital-status         occupation   relationship   race     sex  \
28404       Never-married  Machine-op-inspct      Unmarried  Black    Male   
22674       Never-married  Machine-op-inspct      Own-child  White    Male   
13386  Married-civ-spouse       Craft-repair        Husband  White    Male   
22936  Married-civ-spouse              Sales        Husband  White    Male   
26859       Never-married  Machine-op-inspct      Own-child  White    Male   
...                   ...                ...            ...    ...     ...   
13419  Married-civ-spouse              Sales        Husband  White    Male   
26348  Married-civ-spouse                NaN        Husband  White    Male   
23605       Never-married     Prof-specialty      Own-child  White  Female   
18762       Never-married     Prof-specialty      Own-child  White    Male   
25354       Never-married     Prof-specialty  Not-in-family  White    Male   

       capital-gain  capital-loss  hours-per-week native-country AnnualIncome  
28404             0             0              40  United-States        <=50K  
22674             0             0              43  United-States        <=50K  
13386             0             0              44  United-States        <=50K  
22936             0             0              40  United-States        <=50K  
26859             0             0              40  United-States        <=50K  
...             ...           ...             ...            ...          ...  
13419             0             0              50  United-States         >50K  
26348             0             0              41  United-States         >50K  
23605             0             0              15  United-States        <=50K  
18762             0             0              40  United-States        <=50K  
25354             0             0              99  United-States        <=50K  

[200 rows x 15 columns]

In [16]:
data['workclass'].value_counts()

Private             22696
Self-emp-not-inc     2541
Local-gov            2093
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: workclass, dtype: int64

In [17]:
data.groupby('workclass')['capital-gain'].mean()

workclass
Federal-gov          833.232292
Local-gov            880.202580
Never-worked           0.000000
Private              889.217792
Self-emp-inc        4875.693548
Self-emp-not-inc    1886.061787
State-gov            701.699538
Without-pay          487.857143
Name: capital-gain, dtype: float64

In [18]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
data['workclass'] = labelencoder.fit_transform(data['workclass'])
data['education'] = labelencoder.fit_transform(data['education'])
data['marital-status'] = labelencoder.fit_transform(data['marital-status'])
data['occupation'] = labelencoder.fit_transform(data['occupation'])
data['relationship'] = labelencoder.fit_transform(data['relationship'])
data['race'] = labelencoder.fit_transform(data['race'])
data['sex'] = labelencoder.fit_transform(data['sex'])
data['native-country'] = labelencoder.fit_transform(data['native-country'])

In [19]:
data['AnnualIncome'] = labelencoder.fit_transform(data['AnnualIncome'])

In [20]:
x=data.iloc[:,:-1]
x
y=data.iloc[:,-1]
y

0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    1
32558    0
32559    0
32560    1
Name: AnnualIncome, Length: 32561, dtype: int32

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import *

In [22]:
m1=LogisticRegression()
x_train, x_test, y_train, y_test=train_test_split(x,y, train_size=0.70, random_state=0)
m1.fit(x_train, y_train)
p1=m1.predict(x_test)

In [23]:
#prediction of logistic reg
p1[:20]

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [24]:
m2=DecisionTreeClassifier()
x_train, x_test, y_train, y_test=train_test_split(x,y, train_size=0.70, random_state=0)
m2.fit(x_train, y_train)
p2=m2.predict(x_test)

In [25]:
#prediction of Decision tree reg
p2[:20]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [26]:
m3=RandomForestClassifier()
x_train, x_test, y_train, y_test=train_test_split(x,y, train_size=0.70, random_state=0)
m3.fit(x_train, y_train)
p3=m3.predict(x_test)

In [27]:
#prediction of Decision tree reg
p3[:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [28]:
print('Accuracy of Logistic Regression Model: ')
print(accuracy_score(y_test, p1))
print('Accuracy of Decision Tree Model: ')
print(accuracy_score(y_test, p2))
print('Accuracy of Random Forest Model: ')
print(accuracy_score(y_test, p3))

Accuracy of Logistic Regression Model: 
0.7923021803664654
Accuracy of Decision Tree Model: 
0.8068379568021292
Accuracy of Random Forest Model: 
0.8552564233800799


In [29]:
print('Confusion Matrix of Logistic Regression Model: ')
print(confusion_matrix(y_test, p1))
print('Confusion Matrix of Decision Tree Model: ')
print(confusion_matrix(y_test, p2))
print('Confusion Matrix of Random Forest Model: ')
print(confusion_matrix(y_test, p3))

Confusion Matrix of Logistic Regression Model: 
[[7042  365]
 [1664  698]]
Confusion Matrix of Decision Tree Model: 
[[6433  974]
 [ 913 1449]]
Confusion Matrix of Random Forest Model: 
[[6878  529]
 [ 885 1477]]


In [30]:
print('Classification Report of Logistic Regression Model: ')
print(classification_report(y_test, p1))
print('Classification Report of Decision Tree Model: ')
print(classification_report(y_test, p2))
print('Classification Report of Random Forest Model: ')
print(classification_report(y_test, p3))

Classification Report of Logistic Regression Model: 
              precision    recall  f1-score   support

           0       0.81      0.95      0.87      7407
           1       0.66      0.30      0.41      2362

    accuracy                           0.79      9769
   macro avg       0.73      0.62      0.64      9769
weighted avg       0.77      0.79      0.76      9769

Classification Report of Decision Tree Model: 
              precision    recall  f1-score   support

           0       0.88      0.87      0.87      7407
           1       0.60      0.61      0.61      2362

    accuracy                           0.81      9769
   macro avg       0.74      0.74      0.74      9769
weighted avg       0.81      0.81      0.81      9769

Classification Report of Random Forest Model: 
              precision    recall  f1-score   support

           0       0.89      0.93      0.91      7407
           1       0.74      0.63      0.68      2362

    accuracy                       